version: '2.1'
services:
  api-gateway-1:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      USERS_URL: '192.168.99.101'
      USERS_PORT: '3001'
      USERS_ENTRY: 'users'
      USERS_SIGNUP_ENTRY: 'signup'
      USERS_LOGIN_ENTRY: 'login'
    ports:
      - '5000:5000'
